name: Release app (preview)

on:
  push:
    branches: ['release/*']

jobs:
  setup:
    outputs:
      version: ${{ steps.app_version.outputs.version }}
      ios_version: ${{ steps.ios_app_version.outputs.ios_version }}
    steps:
      - uses: eas/checkout
      - run: git fetch --unshallow
      - run: git config --global user.name "Expo Workflows"
      - run: cd .build && npm install
      - id: app_version
        run: |
          cd .build && APP_VERSION=$(node staging-version.js)
          set-output version "$APP_VERSION"
      - id: ios_app_version 
        run: |
          cd .build && IOS_APP_VERSION=$(node staging-version.js --ios)
          set-output ios_version "$IOS_APP_VERSION"
      - run: git tag -a v${{ steps.app_version.outputs.version }} -m "Version ${{ steps.app_version.outputs.version }}" && git push origin tag v${{ steps.app_version.outputs.version }}

  build_ios:
    needs: [setup]
    type: build
    env:
      APP_VERSION: ${{ needs.setup.outputs.ios_version }}
    params:
      profile: preview # Default EAS profile
      platform: ios

  build_android:
    needs: [setup]
    type: build
    env:
      APP_VERSION: ${{ needs.setup.outputs.version }}
    params:
      profile: preview # Default EAS profile
      platform: android

  submit_ios:
    name: Submit iOS Build
    needs: [build_ios]
    type: submit
    params:
      profile: preview # Default EAS profile
      build_id: ${{ needs.build_ios.outputs.build_id }}

  submit_android:
    name: Submit Android Build
    needs: [build_android]
    type: submit
    params:
      profile: preview # Default EAS profile
      build_id: ${{ needs.build_android.outputs.build_id }}